"""Add ConfiguracionAlquiler

Revision ID: 294b0287a9b5
Revises: 
Create Date: 2026-01-11 23:45:40.490518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '294b0287a9b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_alquiler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dias_incautacion', sa.Integer(), nullable=False),
    sa.Column('porcentaje_mora', sa.Float(), nullable=False),
    sa.Column('usuario_actualizo_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora_actualizo', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_actualizo_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alquileres', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('idx_alquileres_fecha_fin')
        batch_op.drop_index('idx_alquileres_fecha_inicio')
        batch_op.create_index(batch_op.f('ix_alquileres_fecha_alquiler_fin'), ['fecha_alquiler_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_alquileres_fecha_alquiler_inicio'), ['fecha_alquiler_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_alquileres_inquilino_id'), ['inquilino_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alquileres_vehiculo_id'), ['vehiculo_id'], unique=False)

    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.alter_column('cuenta',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('cedula',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_index('idx_estado')
        batch_op.drop_index('idx_fecha_fin')
        batch_op.drop_index('idx_fecha_inicio')
        batch_op.drop_index('idx_inquilino')
        batch_op.drop_index('idx_vehiculo')
        batch_op.create_index(batch_op.f('ix_contratos_fecha_fin'), ['fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_fecha_inicio'), ['fecha_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_inquilino_id'), ['inquilino_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_vehiculo_id'), ['vehiculo_id'], unique=False)

    with op.batch_alter_table('depositos', schema=None) as batch_op:
        batch_op.drop_index('idx_contrato')
        batch_op.drop_index('idx_estado')
        batch_op.drop_index('idx_inquilino')
        batch_op.drop_index('idx_tipo_vehiculo')
        batch_op.drop_index('idx_vehiculo')
        batch_op.create_index(batch_op.f('ix_depositos_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_depositos_inquilino_id'), ['inquilino_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_depositos_tipo_vehiculo'), ['tipo_vehiculo'], unique=False)
        batch_op.create_index(batch_op.f('ix_depositos_vehiculo_id'), ['vehiculo_id'], unique=False)

    with op.batch_alter_table('detalles_alquiler_semanal', schema=None) as batch_op:
        batch_op.alter_column('alquiler_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_index('idx_inquilino')
        batch_op.drop_index('idx_pago_confirmado')
        batch_op.drop_index('idx_propietario')
        batch_op.drop_index('idx_semana')
        batch_op.drop_index('idx_vehiculo')
        batch_op.create_index(batch_op.f('ix_detalles_alquiler_semanal_alquiler_id'), ['alquiler_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detalles_alquiler_semanal_inquilino_id'), ['inquilino_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detalles_alquiler_semanal_propietario_id'), ['propietario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detalles_alquiler_semanal_semana_alquiler_id'), ['semana_alquiler_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detalles_alquiler_semanal_vehiculo_id'), ['vehiculo_id'], unique=False)

    with op.batch_alter_table('deudas', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.create_index(batch_op.f('ix_deudas_fecha_vencimiento'), ['fecha_vencimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_deudas_inquilino_id'), ['inquilino_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deudas_vehiculo_id'), ['vehiculo_id'], unique=False)

    with op.batch_alter_table('estados_alquiler', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('nombre')
        batch_op.create_index(batch_op.f('ix_estados_alquiler_nombre'), ['nombre'], unique=True)

    with op.batch_alter_table('garantes_inquilinos', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.create_index(batch_op.f('ix_garantes_inquilinos_inquilino_id'), ['inquilino_id'], unique=False)

    with op.batch_alter_table('historico_alquileres', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_bancos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('cuenta',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('cedula',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_contratos', schema=None) as batch_op:
        batch_op.drop_index('idx_fecha_operacion')
        batch_op.drop_index('idx_id')

    with op.batch_alter_table('historico_depositos', schema=None) as batch_op:
        batch_op.drop_index('idx_fecha_operacion')
        batch_op.drop_index('idx_id')

    with op.batch_alter_table('historico_deudas', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_estados_alquiler', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_garantes_inquilinos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('nombre_apellido',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('direccion',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('documento_referencia_laboral_path',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.drop_column('cedula')
        batch_op.drop_column('cedula_path')

    with op.batch_alter_table('historico_inquilinos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('nombre_apellido',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('direccion',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('documento_buena_conducta_path',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('cedula',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('cedula_path',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('licencia',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('licencia_path',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_mecanicos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_metodos_pago', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_pagos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_parentescos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('parentesco',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_piezas', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_piezas_usadas', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_porcentajes_ganancia', schema=None) as batch_op:
        batch_op.drop_index('idx_fecha_operacion')
        batch_op.drop_index('idx_tipo_operacion')

    with op.batch_alter_table('historico_propietarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('nombre_apellido',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('documento_buena_conducta_path',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('cedula',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('cedula_path',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('licencia',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('licencia_path',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('direccion',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_referencias_inquilinos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('nombre_apellido',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.drop_column('cedula')
        batch_op.drop_column('cedula_path')

    with op.batch_alter_table('historico_referencias_propietarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('nombre_apellido',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.drop_column('cedula')
        batch_op.drop_column('cedula_path')

    with op.batch_alter_table('historico_semanas_alquiler', schema=None) as batch_op:
        batch_op.drop_index('idx_fecha_operacion')
        batch_op.drop_index('idx_tipo_operacion')

    with op.batch_alter_table('historico_tipo_cuentas', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_tipos_trabajos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_trabajos_vehiculos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_usuarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_vehiculo_marca_modelo', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('historico_vehiculos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))

    with op.batch_alter_table('inquilinos', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('cedula')
        batch_op.drop_index('idx_inquilinos_cedula', mysql_length={'cedula': 768})
        batch_op.drop_index('licencia')
        batch_op.create_index(batch_op.f('ix_inquilinos_nombre_apellido'), ['nombre_apellido'], unique=False)

    with op.batch_alter_table('mecanicos', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('idx_mecanicos_activo')
        batch_op.drop_index('idx_mecanicos_nombre')
        batch_op.create_index(batch_op.f('ix_mecanicos_nombre'), ['nombre'], unique=False)

    with op.batch_alter_table('metodos_pago', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('nombre')
        batch_op.create_index(batch_op.f('ix_metodos_pago_nombre'), ['nombre'], unique=True)

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('idx_pagos_fecha')
        batch_op.create_index(batch_op.f('ix_pagos_alquiler_id'), ['alquiler_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_fecha_pago'), ['fecha_pago'], unique=False)

    with op.batch_alter_table('parentescos', schema=None) as batch_op:
        batch_op.alter_column('parentesco',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('parentesco')

    with op.batch_alter_table('piezas', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.create_index(batch_op.f('ix_piezas_nombre'), ['nombre'], unique=False)

    with op.batch_alter_table('piezas_usadas', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.create_index(batch_op.f('ix_piezas_usadas_trabajo_id'), ['trabajo_id'], unique=False)

    with op.batch_alter_table('porcentajes_ganancia', schema=None) as batch_op:
        batch_op.drop_index('idx_activo')
        batch_op.drop_index('idx_por_defecto')

    with op.batch_alter_table('propietarios', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('cedula')
        batch_op.drop_index('idx_propietarios_cedula', mysql_length={'cedula': 768})
        batch_op.drop_index('licencia')

    with op.batch_alter_table('referencias_inquilinos', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.create_index(batch_op.f('ix_referencias_inquilinos_inquilino_id'), ['inquilino_id'], unique=False)

    with op.batch_alter_table('referencias_propietarios', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.create_index(batch_op.f('ix_referencias_propietarios_propietario_id'), ['propietario_id'], unique=False)

    with op.batch_alter_table('registro_acceso', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.create_index(batch_op.f('ix_registro_acceso_fecha_hora'), ['fecha_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_acceso_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('semanas_alquiler', schema=None) as batch_op:
        batch_op.drop_index('idx_anio')
        batch_op.drop_index('idx_estado')
        batch_op.drop_index('idx_fecha_fin')
        batch_op.drop_index('idx_fecha_inicio')
        batch_op.create_index(batch_op.f('ix_semanas_alquiler_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_semanas_alquiler_fecha_fin'), ['fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_semanas_alquiler_fecha_inicio'), ['fecha_inicio'], unique=False)

    with op.batch_alter_table('tipo_cuentas', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('tipo_cuenta')
        batch_op.create_index(batch_op.f('ix_tipo_cuentas_tipo_cuenta'), ['tipo_cuenta'], unique=True)

    with op.batch_alter_table('tipos_depositos', schema=None) as batch_op:
        batch_op.drop_index('idx_activo')
        batch_op.drop_index('idx_tipo_vehiculo')
        batch_op.drop_index('tipo_vehiculo')
        batch_op.create_index(batch_op.f('ix_tipos_depositos_tipo_vehiculo'), ['tipo_vehiculo'], unique=True)

    with op.batch_alter_table('tipos_trabajos', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('idx_tipos_trabajos_nombre')
        batch_op.drop_index('nombre')
        batch_op.create_index(batch_op.f('ix_tipos_trabajos_nombre'), ['nombre'], unique=True)

    with op.batch_alter_table('trabajos_vehiculos', schema=None) as batch_op:
        batch_op.alter_column('mecanico_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('idx_trabajos_vehiculos_estado')
        batch_op.drop_index('idx_trabajos_vehiculos_fecha')
        batch_op.drop_index('idx_trabajos_vehiculos_mecanico')
        batch_op.drop_index('idx_trabajos_vehiculos_vehiculo')
        batch_op.create_index(batch_op.f('ix_trabajos_vehiculos_fecha_inicio'), ['fecha_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_trabajos_vehiculos_vehiculo_id'), ['vehiculo_id'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index('email')
        batch_op.drop_index('username')
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    with op.batch_alter_table('vehiculo_marca_modelo', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.create_index(batch_op.f('ix_vehiculo_marca_modelo_marca'), ['marca'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculo_marca_modelo_modelo'), ['modelo'], unique=False)

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('idx_vehiculos_placa', mysql_length={'placa': 768})
        batch_op.drop_index('placa')
        batch_op.create_index(batch_op.f('ix_vehiculos_placa'), ['placa'], unique=True)
        batch_op.create_index(batch_op.f('ix_vehiculos_propietario_id'), ['propietario_id'], unique=False)

    with op.batch_alter_table('vehiculos_imagenes', schema=None) as batch_op:
        batch_op.drop_index('idx_vehiculo')
        batch_op.create_index(batch_op.f('ix_vehiculos_imagenes_vehiculo_id'), ['vehiculo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos_imagenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiculos_imagenes_vehiculo_id'))
        batch_op.create_index('idx_vehiculo', ['vehiculo_id'], unique=False)

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiculos_propietario_id'))
        batch_op.drop_index(batch_op.f('ix_vehiculos_placa'))
        batch_op.create_index('placa', ['placa'], unique=False)
        batch_op.create_index('idx_vehiculos_placa', ['placa'], unique=False, mysql_length={'placa': 768})
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('vehiculo_marca_modelo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiculo_marca_modelo_modelo'))
        batch_op.drop_index(batch_op.f('ix_vehiculo_marca_modelo_marca'))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.create_index('username', ['username'], unique=False)
        batch_op.create_index('email', ['email'], unique=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('trabajos_vehiculos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trabajos_vehiculos_vehiculo_id'))
        batch_op.drop_index(batch_op.f('ix_trabajos_vehiculos_fecha_inicio'))
        batch_op.create_index('idx_trabajos_vehiculos_vehiculo', ['vehiculo_id'], unique=False)
        batch_op.create_index('idx_trabajos_vehiculos_mecanico', ['mecanico_id'], unique=False)
        batch_op.create_index('idx_trabajos_vehiculos_fecha', ['fecha_inicio'], unique=False)
        batch_op.create_index('idx_trabajos_vehiculos_estado', ['estado'], unique=False)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('mecanico_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('tipos_trabajos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipos_trabajos_nombre'))
        batch_op.create_index('nombre', ['nombre'], unique=False)
        batch_op.create_index('idx_tipos_trabajos_nombre', ['nombre'], unique=False)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('tipos_depositos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipos_depositos_tipo_vehiculo'))
        batch_op.create_index('tipo_vehiculo', ['tipo_vehiculo'], unique=False)
        batch_op.create_index('idx_tipo_vehiculo', ['tipo_vehiculo'], unique=False)
        batch_op.create_index('idx_activo', ['activo'], unique=False)

    with op.batch_alter_table('tipo_cuentas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipo_cuentas_tipo_cuenta'))
        batch_op.create_index('tipo_cuenta', ['tipo_cuenta'], unique=False)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('semanas_alquiler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semanas_alquiler_fecha_inicio'))
        batch_op.drop_index(batch_op.f('ix_semanas_alquiler_fecha_fin'))
        batch_op.drop_index(batch_op.f('ix_semanas_alquiler_anio'))
        batch_op.create_index('idx_fecha_inicio', ['fecha_inicio'], unique=False)
        batch_op.create_index('idx_fecha_fin', ['fecha_fin'], unique=False)
        batch_op.create_index('idx_estado', ['estado'], unique=False)
        batch_op.create_index('idx_anio', ['anio'], unique=False)

    with op.batch_alter_table('registro_acceso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_acceso_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_registro_acceso_fecha_hora'))
        batch_op.alter_column('fecha_hora',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('referencias_propietarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referencias_propietarios_propietario_id'))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('referencias_inquilinos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referencias_inquilinos_inquilino_id'))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('propietarios', schema=None) as batch_op:
        batch_op.create_index('licencia', ['licencia'], unique=False)
        batch_op.create_index('idx_propietarios_cedula', ['cedula'], unique=False, mysql_length={'cedula': 768})
        batch_op.create_index('cedula', ['cedula'], unique=False)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('porcentajes_ganancia', schema=None) as batch_op:
        batch_op.create_index('idx_por_defecto', ['por_defecto'], unique=False)
        batch_op.create_index('idx_activo', ['activo'], unique=False)

    with op.batch_alter_table('piezas_usadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_piezas_usadas_trabajo_id'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('piezas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_piezas_nombre'))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('parentescos', schema=None) as batch_op:
        batch_op.create_index('parentesco', ['parentesco'], unique=False)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('parentesco',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_fecha_pago'))
        batch_op.drop_index(batch_op.f('ix_pagos_alquiler_id'))
        batch_op.create_index('idx_pagos_fecha', ['fecha_pago'], unique=False)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('metodos_pago', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metodos_pago_nombre'))
        batch_op.create_index('nombre', ['nombre'], unique=False)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('mecanicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mecanicos_nombre'))
        batch_op.create_index('idx_mecanicos_nombre', ['nombre'], unique=False)
        batch_op.create_index('idx_mecanicos_activo', ['activo'], unique=False)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('inquilinos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inquilinos_nombre_apellido'))
        batch_op.create_index('licencia', ['licencia'], unique=False)
        batch_op.create_index('idx_inquilinos_cedula', ['cedula'], unique=False, mysql_length={'cedula': 768})
        batch_op.create_index('cedula', ['cedula'], unique=False)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('historico_vehiculos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_vehiculo_marca_modelo', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_usuarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_trabajos_vehiculos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_tipos_trabajos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_tipo_cuentas', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_semanas_alquiler', schema=None) as batch_op:
        batch_op.create_index('idx_tipo_operacion', ['tipo_operacion'], unique=False)
        batch_op.create_index('idx_fecha_operacion', ['fecha_hora_operacion'], unique=False)

    with op.batch_alter_table('historico_referencias_propietarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('cedula', mysql.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nombre_apellido',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_referencias_inquilinos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('cedula', mysql.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nombre_apellido',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_propietarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('direccion',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('licencia_path',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('licencia',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cedula_path',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cedula',
               existing_type=sa.String(length=20),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('documento_buena_conducta_path',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nombre_apellido',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_porcentajes_ganancia', schema=None) as batch_op:
        batch_op.create_index('idx_tipo_operacion', ['tipo_operacion'], unique=False)
        batch_op.create_index('idx_fecha_operacion', ['fecha_hora_operacion'], unique=False)

    with op.batch_alter_table('historico_piezas_usadas', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_piezas', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_parentescos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('parentesco',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_pagos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_metodos_pago', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_mecanicos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_inquilinos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('licencia_path',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('licencia',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cedula_path',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cedula',
               existing_type=sa.String(length=20),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('documento_buena_conducta_path',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('direccion',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nombre_apellido',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_garantes_inquilinos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('cedula', mysql.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('documento_referencia_laboral_path',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('direccion',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nombre_apellido',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_estados_alquiler', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_deudas', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_depositos', schema=None) as batch_op:
        batch_op.create_index('idx_id', ['id'], unique=False)
        batch_op.create_index('idx_fecha_operacion', ['fecha_hora_operacion'], unique=False)

    with op.batch_alter_table('historico_contratos', schema=None) as batch_op:
        batch_op.create_index('idx_id', ['id'], unique=False)
        batch_op.create_index('idx_fecha_operacion', ['fecha_hora_operacion'], unique=False)

    with op.batch_alter_table('historico_bancos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('cedula',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('cuenta',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('historico_alquileres', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('fecha_hora_operacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('garantes_inquilinos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garantes_inquilinos_inquilino_id'))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('estados_alquiler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estados_alquiler_nombre'))
        batch_op.create_index('nombre', ['nombre'], unique=False)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('deudas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deudas_vehiculo_id'))
        batch_op.drop_index(batch_op.f('ix_deudas_inquilino_id'))
        batch_op.drop_index(batch_op.f('ix_deudas_fecha_vencimiento'))
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('detalles_alquiler_semanal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detalles_alquiler_semanal_vehiculo_id'))
        batch_op.drop_index(batch_op.f('ix_detalles_alquiler_semanal_semana_alquiler_id'))
        batch_op.drop_index(batch_op.f('ix_detalles_alquiler_semanal_propietario_id'))
        batch_op.drop_index(batch_op.f('ix_detalles_alquiler_semanal_inquilino_id'))
        batch_op.drop_index(batch_op.f('ix_detalles_alquiler_semanal_alquiler_id'))
        batch_op.create_index('idx_vehiculo', ['vehiculo_id'], unique=False)
        batch_op.create_index('idx_semana', ['semana_alquiler_id'], unique=False)
        batch_op.create_index('idx_propietario', ['propietario_id'], unique=False)
        batch_op.create_index('idx_pago_confirmado', ['pago_confirmado'], unique=False)
        batch_op.create_index('idx_inquilino', ['inquilino_id'], unique=False)
        batch_op.alter_column('alquiler_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('depositos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depositos_vehiculo_id'))
        batch_op.drop_index(batch_op.f('ix_depositos_tipo_vehiculo'))
        batch_op.drop_index(batch_op.f('ix_depositos_inquilino_id'))
        batch_op.drop_index(batch_op.f('ix_depositos_contrato_id'))
        batch_op.create_index('idx_vehiculo', ['vehiculo_id'], unique=False)
        batch_op.create_index('idx_tipo_vehiculo', ['tipo_vehiculo'], unique=False)
        batch_op.create_index('idx_inquilino', ['inquilino_id'], unique=False)
        batch_op.create_index('idx_estado', ['estado'], unique=False)
        batch_op.create_index('idx_contrato', ['contrato_id'], unique=False)

    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_vehiculo_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_inquilino_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_fecha_inicio'))
        batch_op.drop_index(batch_op.f('ix_contratos_fecha_fin'))
        batch_op.create_index('idx_vehiculo', ['vehiculo_id'], unique=False)
        batch_op.create_index('idx_inquilino', ['inquilino_id'], unique=False)
        batch_op.create_index('idx_fecha_inicio', ['fecha_inicio'], unique=False)
        batch_op.create_index('idx_fecha_fin', ['fecha_fin'], unique=False)
        batch_op.create_index('idx_estado', ['estado'], unique=False)

    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('usuario_actualizo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('cedula',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('cuenta',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('alquileres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alquileres_vehiculo_id'))
        batch_op.drop_index(batch_op.f('ix_alquileres_inquilino_id'))
        batch_op.drop_index(batch_op.f('ix_alquileres_fecha_alquiler_inicio'))
        batch_op.drop_index(batch_op.f('ix_alquileres_fecha_alquiler_fin'))
        batch_op.create_index('idx_alquileres_fecha_inicio', ['fecha_alquiler_inicio'], unique=False)
        batch_op.create_index('idx_alquileres_fecha_fin', ['fecha_alquiler_fin'], unique=False)
        batch_op.alter_column('fecha_hora_actualizo',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('fecha_hora_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('usuario_registro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    op.drop_table('configuracion_alquiler')
    # ### end Alembic commands ###
